
import { BackButton } from '@/components/back-to-home-button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import Script from 'next/script';

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-7xl mx-auto space-y-8 px-4 sm:px-0" data-ai-id="privacy-page-container">
      <BackButton />
      <Card data-ai-id="privacy-card">
        <CardHeader>
          <CardTitle className="text-3xl font-bold text-primary" data-ai-id="privacy-heading">Privacy Policy</CardTitle>
          <p className="text-sm text-muted-foreground" data-ai-id="privacy-last-updated">Last updated: NOV 9, 2025</p>
        </CardHeader>
        <CardContent>
          <article className="space-y-6 prose dark:prose-invert max-w-none" data-ai-id="privacy-article">
            <p data-ai-id="privacy-intro">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <section>
                <h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>
                <h3 className="text-xl font-semibold mt-4">Interpretation</h3>
                <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
                <h3 className="text-xl font-semibold mt-4">Definitions</h3>
                <p>For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 space-y-2">
                    <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                    <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to vtuadda.</li>
                    <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                    <li><strong>Country</strong> refers to: Karnataka, India</li>
                    <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                    <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                    <li><strong>Service</strong> refers to the Website.</li>
                    <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
                    <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
                    <li><strong>Website</strong> refers to vtuadda, accessible from https://vtuadda.com</li>
                    <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
            </section>
            
            <section>
                <h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
                <h3 className="text-xl font-semibold mt-4">Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, Phone number, and Usage Data.</p>
                <h4>Usage Data</h4>
                <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device’s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                <h4>Tracking Technologies and Cookies</h4>
                <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
            </section>
            
            <section>
                <h2 className="text-2xl font-semibold">Use of Your Personal Data</h2>
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-2">
                    <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                    <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                    <li><strong>To contact You:</strong> To contact You by email or other forms of electronic communication.</li>
                    <li><strong>To provide You with news,</strong> special offers and general information about other goods, services and events.</li>
                    <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
                    <li><strong>For other purposes:</strong> such as data analysis, identifying usage trends, and to evaluate and improve our Service.</li>
                </ul>
            </section>

            <section>
                <h2 className="text-2xl font-semibold">Retention and Transfer of Your Personal Data</h2>
                <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. The Company will also retain Usage Data for internal analysis purposes.</p>
                <p>Your information, including Personal Data, is processed at the Company’s operating offices and in any other places where the parties involved in the processing are located. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
            </section>
            
            <section>
                <h2 className="text-2xl font-semibold">Disclosure of Your Personal Data</h2>
                <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            </section>

            <section data-ai-id="privacy-section-third-party">
                <h2 className="text-2xl font-semibold" data-ai-id="privacy-heading-third-party">Third-Party Services</h2>
                <p data-ai-id="privacy-text-third-party">
                    We use third-party services like Google AdSense and Google Analytics, which may also collect and use your data. Their use of your information is governed by their respective privacy policies.
                </p>
                <ul className="list-disc pl-6 space-y-2" data-ai-id="privacy-third-party-list">
                    <li data-ai-id="privacy-third-party-adsense"><strong>Google AdSense:</strong> We use Google AdSense to display ads. Google may use cookies to serve ads based on a user's prior visits to our website or other websites. You may opt out of personalized advertising by visiting Google's Ads Settings.</li>
                    <li data-ai-id="privacy-third-party-analytics"><strong>Google Analytics:</strong> We use Google Analytics to understand our website traffic. This service tracks and reports website traffic. This data is shared with other Google services.</li>
                </ul>
            </section>

            <section>
                <h2 className="text-2xl font-semibold">Security of Your Personal Data</h2>
                <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
            </section>

            <section>
                <h2 className="text-2xl font-semibold">Children’s Privacy</h2>
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.</p>
            </section>

            <section>
                <h2 className="text-2xl font-semibold">Links to Other Websites</h2>
                <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party’s site. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
            </section>

            <section>
                <h2 className="text-2xl font-semibold">Changes to this Privacy Policy</h2>
                <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold">Contact Us</h2>
              <p>If you have any questions about this Privacy Policy, you can contact us:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>By email: thevtuadda@gmail.com</li>
                <li>By visiting our contact section: <a href="/contact" className="text-primary hover:underline">vtuadda.com/contact</a></li>
              </ul>
            </section>
          </article>
        </CardContent>
      </Card>
    </div>
  );
}
